apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: shredder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: shredder
spec:
  type: NodePort  # Change to LoadBalancer for production on EKS
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30889
  selector:
    app: nginx