apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: shredder
spec:
  storageClassName: shredder-storage
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce